### ISSUE TITLE
解压失败的文件，如何恢复它原来的文件名称

### ISSUE THREAD

**Issue by wzgrx** [ssh-buanshishi/f-keydle______Multilayer-Compression--and--single-chained---Folder-Nesting--handler#1]
【_解压失败_】0101-0200【_dot_】7z【_dot_】001【_解压失败_】.【_解压失败_】
![Snipaste_2023-10-09_08-54-25](https://github.com/ssh-buanshishi/f-keydle______Multilayer-Compression--and--single-chained---Folder-Nesting--handler/assets/39661556/295d6247-0c43-47e7-8005-9ad178bf98d2)

**Comment by ssh-buanshishi** [comment]
先把“.【_解压失败_】”替换删除，再把“【_解压失败_】”替换删除，最后把“【_dot_】”替换为“.”

**Comment by ssh-buanshishi** [comment]
新的v2.1版本出来后，可将含有被标记文件的文件夹拖放至“【【清除程序残留文件+恢复被标记文件】】.bat”上进行处理。

@wzgrx 兄弟这个issue暂时不要关哈，我准备先把这条新消息晾个一段时间之后再说😁
当然，如果一两个月以后谁还记得的话，可以帮我close一下。
